### ISSUE TITLE
Washing Machine HWE 49AMBS/1-S Data Archive

### ISSUE THREAD

**Issue by nimda95** [Andre0512/hon-test-data#11]
[wm_48.zip](https://github.com/Andre0512/hon-test-data/files/12190997/wm_48.zip)

Washing machine is perfectly working with this integration, but wanted to add-it just if it might help.

Good work y'aall 😄 , and Thanks ❤️

**Comment by Andre0512** [comment]
Thanks @nimda95! :partying_face:
