### ISSUE TITLE
AS09TS4HRA-M Air Cond Data Archive

### ISSUE THREAD

**Issue by tmv002** [Andre0512/hon-test-data#2]
[ac_555.zip](https://github.com/Andre0512/hon-test-data/files/11934686/ac_555.zip)
All sensor works perfect, air conditioner control not working

**Comment by Andre0512** [comment]
Thanks for your contribution @tmv002! 🙂 
If something doesn't work, can you open a new issue in [hon](https://github.com/Andre0512/hon) and explain what's wrong? (if possible with logs, screenshots, reproducing steps, ...).
