### ISSUE TITLE
Dishwasher Candy CF 3C7L0X

### ISSUE THREAD

**Issue by traxxxto** [Andre0512/hon-test-data#20]
Can you add this appliance to suported devices? 
Dishwasher Candy CF 3C7L0X

Here is the Zip file generated with home assistant integration.

[dw_12658.zip](https://github.com/Andre0512/hon-test-data/files/13881223/dw_12658.zip)

Thank you in advance for your time.

**Comment by Andre0512** [comment]
Hi, thanks for sharing! I see there are some new options, I will add them to the hOn integration :slightly_smiling_face:
