### ISSUE TITLE
HWC 150 EELW/N not recognized

### ISSUE THREAD

**Issue by GeraldPape** [Andre0512/hon-test-data#24]
executing the commands:
```
PS C:\code\winecellar\hon-test-data> pyhOn export --anonymous test_data/
User for hOn account: email@mail.com
Password for hOn account:
PS C:\code\winecellar\hon-test-data> 
```
results in no data.

Attached a screenshot of whats in the app

![Bildschirmfoto 2024-02-07 um 14 45 18](https://github.com/Andre0512/hon-test-data/assets/72608781/765f5153-906c-450f-847b-528e19ba630f)

**Comment by Andre0512** [comment]
Hi, this integration is not compatible with Hoover Wizard. If you can't get your device running with the hOn app, I'm afraid that will not work...
